select *
FROM EMP;

SELECT JOB
FROM EMP;

SELECT DISTINCT JOB
FROM EMP;

SELECT DISTINCT ENAME,JOB
FROM EMP;

--선수들의 정보를 모두 조회하시오.

SELECT *
FROM PLAYER;

SELECT  EMPNO 사원번호, ENAME 사원이름, MGR "사원의 직속상사 번호", DEPTNO 부서번호
FROM EMP;

SELECT DEPTNO 부서번호, DNAME "name", LOC "Location", DEPTNO AS "부서Number"
FROM DEPT;

DESC PLAYER;

SELECT PLAYER_NAME "선수 이름", POSITION "포지션 위치", WEIGHT 키, HEIGHT 몸무게
FROM PLAYER;

SELECT ENAME, SAL, (SAL*12)*1000
FROM EMP;

SELECT PLAYER_NAME 이름, HEIGHT - WEIGHT "키-몸무게"
FROM PLAYER;

SELECT PLAYER_NAME 이름, ROUND(WEIGHT / ((HEIGHT*0.01)*(HEIGHT*0.01)), 2) "BMI 비만지수"
FROM PLAYER;

SELECT *
FROM EMP;

SELECT EMPNO||' 사원번호는 '||ENAME||'님이며 직업은 '||JOB||'입니다' 자기소개,
EMPNO||ENAME, '칼럼에 없는 글자만으로도 '||'만들 수 있어'
FROM EMP;

SELECT PLAYER_NAME||' 선수, '||HEIGHT||' cm, '||WEIGHT||' kg' as 체격정보
FROM PLAYER;

INSERT INTO PLAYER
(PLAYER_ID, TEAM_ID, PLAYER_NAME, POSITION, HEIGHT, WEIGHT, BACK_NO)
VALUES('1997035', 'K02', '이운재', 'GK', 182,82,1);

COMMIT;

DELETE FROM PLAYER
WHERE PLAYER_ID = '1997035';

SELECT COUNT(*)
FROM EMP
WHERE JOB = 'CLERK';

SELECT *
FROM EMP
WHERE SAL >= 3000;

SELECT *
FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL <= 1500;

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE HEIGHT >= 170;

select empno, ename, sal
from emp
where ename = 'FORD';

SELECT *
FROM EMP;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE ENAME = 'SMITH';

SELECT *
FROM PLAYER;

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02';

SELECT PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM PLAYER
WHERE POSITION = 'MF';

SELECT *
FROM EMP
WHERE HIREDATE <= '1981/04/02';


SELECT *
FROM EMP
WHERE COMM IN (300, 500, 1400);

SELECT *
FROM EMP
WHERE JOB IN ('SALESMAN', 'ANALYST');

SELECT *
FROM EMP
WHERE DEPTNO NOT IN (20, 30);

SELECT *
FROM EMP;



SELECT EMPNO, SAL
FROM EMP
WHERE EMPNO IN (7521, 7654, 7844);

SELECT EMPNO, ENAME
FROM EMP
WHERE EMPNO NOT IN (7521, 7654, 7902);

SELECT PLAYER_NAME AS 선수이름, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07');

SELECT *
FROM EMP
WHERE ENAME LIKE '%M%';

SELECT *
FROM EMP
WHERE ENAME LIKE '_L%';

SELECT *
FROM EMP
WHERE ENAME LIKE '_L___';


SELECT EMPNO AS 사원번호, ENAME AS 사원명
FROM EMP
WHERE ENAME LIKE 'K%';

SELECT EMPNO AS 사원번호, ENAME AS 사원명
FROM EMP
WHERE ENAME LIKE '%K%';

SELECT EMPNO AS 사원번호, ENAME AS 사원명
FROM EMP
WHERE ENAME LIKE '%K';

SELECT *
FROM EMP
WHERE ENAME LIKE '_A%';


SELECT *
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT *
FROM PLAYER;

SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '80/01/01' AND '80/12/31';

SELECT PLAYER_NAME AS 선수이름, POSITION AS 포지션, NATION AS 국적, NICKNAME AS 별명, HEIGHT AS 키
FROM PLAYER 
WHERE HEIGHT BETWEEN 170 AND 180;


SELECT ENAME, SAL, SAL * 12, SAL * NULL, SAL * NULL
FROM EMP
WHERE COMM IS NULL;

SELECT PLAYER_ID AS 선수ID, E_PLAYER_NAME AS 선수영어이름, POSITION AS 포지션, TEAM_ID AS 팀ID 
FROM PLAYER
WHERE POSITION IS NULL;

SELECT *
FROM EMP
WHERE MGR IS NULL;


SELECT   *
FROM     EMP
WHERE    DEPTNO = 10
AND      JOB = 'MANAGER';

SELECT *
FROM TEAM;

SELECT   *
FROM     PLAYER
WHERE    TEAM_ID IN ('K02', 'K07') 
AND      POSITION = 'MF'
AND      HEIGHT BETWEEN 170 AND 180;

SELECT  *
FROM    EMP
WHERE   DEPTNO = 10
OR      JOB = 'MANAGER';




SELECT  *
FROM    EMP
WHERE   NOT (2000 <= SAL AND 3000 >= SAL);

SELECT  *
FROM    EMP;

SELECT  *
FROM    EMP
WHERE   SAL < 2000 OR SAL > 3000;

SELECT  *
FROM    EMP
WHERE   NOT SAL BETWEEN 2000 AND 3000;

SELECT  *
FROM    PLAYER
WHERE   TEAM_ID = 'K02'
AND     NOT POSITION = 'MF'
AND     NOT (HEIGHT >= 175 AND HEIGHT <= 185);

SELECT  PLAYER_NAME AS 선수이름, NATION AS 국적
FROM    PLAYER
WHERE   NATION IS NOT NULL;