
CREATE TABLE DEPT03
AS
SELECT *
FROM DEPT;

SELECT *
FROM DEPT;

ALTER TABLE DEPT03
MODIFY (DEPTNO NUMBER(4));

ALTER TABLE DEPT03
MODIFY (DNAME VARCHAR(20));

DESC DEPT03;

CREATE TABLE SAM01
AS SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE 1 = 0;

SELECT *
FROM SAM01;

INSERT INTO SAM01
VALUES (1000, 'APPLE', 'POLICE', 10000);

INSERT INTO SAM01
VALUES (1010, 'BANANA', 'NURSE', 15000);

INSERT INTO SAM01 
VALUES (1020, 'ORANGE', 'DOCTOR', 25000);

INSERT INTO SAM01(empno, ENAME, SAL)
VALUES (1030, 'VAT', 2000);

SELECT *
FROM EMP;

CREATE TABLE DEPT01
AS
SELECT *
FROM DEPT;


SELECT *
FROM DEPT01;

UPDATE DEPT01
SET DNAME = 'ACCOUNT'
WHERE DNAME = 'ACCOUNTING';

DELETE FROM DEPT01;

select *
from test;

insert into test
values (1, 'aaa', 10, '');

commit;

select *
from dept;

DESC USER_CONSTRAINTS;

SELECT *
FROM USER_CONSTRAINTS;

SELECT *
FROM EMP01;

DROP TABLE EMP01;

CREATE TABLE EMP01
(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

SELECT *
FROM EMP02;

INSERT INTO EMP02
VALUES (NULL, NULL, 'SALES', 30);

DROP TABLE EMP02;

CREATE TABLE EMP02
(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);


CREATE TABLE PRODUCT
(   PRODUCT_NO NUMBER(2) NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_COMPANY VARCHAR2(100)
);

DESC PRODUCT;

INSERT INTO PRODUCT
VALUES (15, 'I_PHONE', 'APPLE');

INSERT INTO PRODUCT
VALUES (21, 'GALAXY_NOTE', 'SAMSUNG');

INSERT INTO PRODUCT
VALUES (10, '핸드프로', '합격하자');

SELECT *
FROM EMP03;

DELETE FROM EMP01;
COMMIT;
--
--INSERT INTO EMP01
--VALUES (7499, 'AAA;, 'SALES', 30);
--INSERT INTO EMP01
--VALUES (7499, 'BBB', 'MANAGER', 20);

CREATE TABLE EMP03
(
    EMPNO NUMBER(4) UNIQUE,
    ENAME VARCHAR(10) UNIQUE,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

INSERT INTO EMP03
VALUES (7499, 'AAA', 'SALES', 30);
INSERT INTO EMP03
VALUES (7499, 'BBB', 'MANAGER', 20);

DESC DEPT;

CREATE TABLE DEPT04
(   DEPT_NO NUMBER(2) UNIQUE,
    DEPT_NAME VARCHAR2(14),
    DEPT_LOCAL VARCHAR2(13) UNIQUE
);

DESC DEPT04;

INSERT INTO DEPT04
VALUES 
(11, 'SALES', '1F');

INSERT INTO DEPT04
VALUES 
(23, 'PERSONNEL', '2F');

INSERT INTO DEPT04
VALUES 
(35, 'GENERAL_AFFAIR', '3F');

SELECT *
FROM DEPT04;

SELECT *
FROM USER_CONSTRAINTS;

CREATE TABLE EMP04
(
    EMPNO NUMBER(4) CONSTRAINT EMP04_EMPNO_UK UNIQUE,
    ENAME VARCHAR(10) CONSTRAINT EMP04_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

DELETE FROM EMP03;
COMMIT;

INSERT INTO EMP03
VALUES (NULL, 'JONES', 'MANAGER', 20);

INSERT INTO EMP03
VALUES (NULL, 'JONES', 'SALES', 10);

CREATE TABLE EMP05
(
    EMPNO NUMBER(4) CONSTRAINT EMP05_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR(10) CONSTRAINT EMP05_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

INSERT INTO EMP05
VALUES (7000, 'JONES', 'MANAGER', 20);

INSERT INTO EMP05
VALUES (7001, 'JONES', 'SALES', 20);

INSERT INTO EMP05
VALUES (7499, 'ALLEN', 'SALES', 30);

DESC EMP05;

SELECT *
FROM EMP05
WHERE EMPNO = 7001;



CREATE TABLE EPSON
(   SERIAL_NUMBER NUMBER (6)  CONSTRAINT EPSON_SERIAL_NUMBER_PK PRIMARY KEY,
    PRODUCT_NAME VARCHAR2 (15) CONSTRAINT EPSON_PRODUCT_NAME_NN NOT NULL,
    PRICE NUMBER (7) CONSTRAINT EPSON_PRICE_NN NOT NULL    
);

DESC EPSON;

INSERT INTO EPSON
VALUES (1246, 'EPSON_SERIES1', 10000);

INSERT INTO EPSON
VALUES (1457, 'EPSON_SERIES2', 100000);

INSERT INTO EPSON
VALUES (1247, 'EPSON_SERIES1', 20000);

SELECT *
FROM EPSON
WHERE SERIAL_NUMBER = 1247;

ALTER TABLE DEPT
ADD CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO);

SELECT *
FROM USER_CONSTRAINTS;

DESC DEPT;

SELECT *
FROM DEPT;

ALTER TABLE DEPT
DROP CONSTRAINT DEPT_DEPTNO_PK;

SELECT *
FROM EMP06;

CREATE TABLE EMP06
AS
SELECT *
FROM EMP;

INSERT INTO EMP06
(EMPNO, ENAME, DEPTNO)
VALUES
(8000, '홍길동', 50);

ROLLBACK;

DROP TABLE DEPT02;

CREATE TABLE DEPT02
(
    DEPTNO   NUMBER(2) PRIMARY KEY,
    DNAME    VARCHAR2(14),
    LOC      VARCHAR2(13) 
);

DESC EMP;

CREATE TABLE EMP07
(
    EMPNO             NUMBER(4) PRIMARY KEY,    
    ENAME             VARCHAR2(10),
    JOB               VARCHAR2(9),
    MGR               NUMBER(4),    
    HIREDATE          DATE,         
    SAL               NUMBER(7,2),  
    COMM              NUMBER(7,2),  
    DEPTNO            NUMBER(2) CONSTRAINT 
        EMP07_DEPTNO_DEPT02_FK REFERENCES DEPT02(DEPTNO)
);

insert into emp07
(empno, ename, deptno)
values
(7369, 'smith', 20);

insert into emp07
(empno, ename, deptno)
values
(8000, 'ALLEN', 30);

insert into emp07
(empno, ename, deptno)
values
(7369, '홍길동', 50);

INSERT INTO DEPT02
VALUES
(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT02
VALUES
(20, 'RESEARCH', 'DALLAS');

INSERT INTO DEPT02
VALUES
(30, 'SALES', 'CHICAGO');

INSERT INTO DEPT02
VALUES
(40, 'OPERATIONS', 'BOSTON');

SELECT *
FROM DEPT02;

CREATE TABLE SNACK
(
    SERIAL_NUMBER       NUMBER (4)      CONSTRAINT SNACK_SERIAL_NUMBER_PK PRIMARY KEY,
    SNACK_NAME          VARCHAR2(50)    CONSTRAINT SNACK_SNACK_NAME_NN NOT NULL,
    PRICE               NUMBER (5, 1)   CONSTRAINT SNACK_PRICE_NN NOT NULL,
    MANUFACTURE_DATE    DATE
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_NAME       VARCHAR2 (20)   CONSTRAINT CUSTOMER_CUSTOMER_NAME_NN NOT NULL,
    ID_NUMBER           NUMBER(14)      CONSTRAINT CUSTOMER_ID_NUMBER_PK PRIMARY KEY,
    PURCHASING_ITEM     NUMBER (4)      CONSTRAINT PURCHASING_ITEM_FK REFERENCES SNACK(SERIAL_NUMBER)
);

INSERT INTO SNACK
VALUES
(1000, '새우깡', 1000, SYSDATE);

INSERT INTO SNACK
VALUES
(1001, '감자깡', 1200, SYSDATE);

INSERT INTO SNACK
VALUES
(1002, '고구마깡', 1500, SYSDATE);


INSERT INTO CUSTOMER
VALUES
('CLARK', 5432, 1000);

INSERT INTO CUSTOMER
VALUES
('LEWIS', 2457, 1000);

INSERT INTO CUSTOMER
VALUES
('NANA', 5497, 1001);

INSERT INTO CUSTOMER
VALUES
('GEORGE', 2671, 1002);

SELECT *
FROM SNACK;

SELECT *
FROM CUSTOMER;

ALTER TABLE CUSTOMER 
RENAME COLUMN PURCHASING_ITEM TO SERIAL_NUMBER;

select *
from user_constraints;

DESC DEPT03;


INSERT INTO DEPT03
(DEPTNO, DNAME)
VALUES (10, 'ACCOUNTING');

SELECT *
FROM DEPT03;

INSERT INTO DEPT02
(DEPTNO, DNAME)
VALUES (30, 'ACCOUNTING');

SELECT *
FROM DEPT02;

ALTER TABLE DEPT02
ADD DNAME VARCHAR2(20);

SELECT *
FROM EMP06;

SELECT *
FROM USER_CONSTRAINTS;


ALTER TABLE DEPT
ADD CONSTRAINT DEPT_DEPTNO_UK UNIQUE (DEPTNO);

ALTER TABLE DEPT
MODIFY (DNAME NOT NULL);

ALTER TABLE DEPT
MODIFY (LOC NOT NULL);

ALTER TABLE EMP
ADD CONSTRAINT EMP_ENAME_PK PRIMARY KEY (EMPNO);

ALTER TABLE EMP
MODIFY (ENAME NOT NULL);

ALTER TABLE EMP
MODIFY (JOB NOT NULL);

ALTER TABLE EMP
MODIFY (HIREDATE NOT NULL);

ALTER TABLE EMP
MODIFY (SAL NOT NULL);

ALTER TABLE EMP
ADD CONSTRAINT EMP_DEPTNO_FK REFERENCES DEPT(DEPTNO);


ROLLBACK;


