select  player_name, POSITION, BACK_NO, HEIGHT
FROM    PLAYER
WHERE   (TEAM_ID = 'K02' OR TEAM_ID = 'K07')
AND     POSITION = 'MF';

--팀이 삼성블루윙즈이거나 전남드래곤즈인 선수 중에 미드필더 역할을 하고 있는 
--선수를 추려내서 그 선수의 이름, 포지션, 등번호, 키를 검색한다.

SELECT  *
FROM    TEAM;

SELECT  *
FROM EMP
WHERE ROWNUM = 1;

SELECT  *
FROM    EMP
WHERE   ROWNUM <= 10;


SELECT  *
FROM    PLAYER
WHERE   ROWNUM <= 40;

SELECT  24 * 60
FROM    DUAL;

SELECT  -10, ABS(-10)   --절대값
FROM    DUAL;

SELECT  34.5678, FLOOR(34.5678)     --소수점버림
FROM    DUAL;

SELECT  34.5678, ROUND(34.5678, 2)      --반올림  XXX, 2 -> 2번째 소수점까지 반올림
FROM    DUAL;

SELECT  34.5678, ROUND(34.5678, -1)
FROM    DUAL;

SELECT  TRUNC(34.5678, 2), TRUNC(34.5678, -1), TRUNC(34.5678)       --자릿수대로 버림
FROM    DUAL;

SELECT  MOD(27, 2), MOD(27, 5)
FROM    DUAL;

SELECT  *
FROM    EMP;

SELECT  *
FROM    EMP
WHERE   MOD(EMPNO, 2) = 1;

SELECT  LENGTH('SQL Expert')
FROM    DUAL;

SELECT  CONCAT(1, '축구') AS 스포츠
FROM    DUAL;

SELECT  *
FROM    STADIUM;

SELECT  STADIUM_ID, TEL, LENGTH(CONCAT(DDD, TEL)) AS T_LEN
FROM    STADIUM;

SELECT  STADIUM_ID, DDD||TEL AS TEL, LENGTH(DDD||TEL) AS "T_len"
FROM    STADIUM;

SELECT  ENAME, CEIL(SAL / 12)
FROM    EMP;

SELECT  LOWER('SQL Expert')
FROM    DUAL;

SELECT  UPPER('SQL Expert')
FROM    DUAL;

SELECT  SUBSTR('SQL Expert', 5, 3)
FROM    DUAL;

SELECT  LTRIM('xxxYYZZxYZ', 'x')
from    dual;

SELECT  LTRIM('xxxYYZZxZX', 'x')
FROM    DUAL;

SELECT  RTRIM('xxxYYZZxYZ', 'x')
FROM    DUAL;



SELECT  UPPER ('Welcome to Oracle')
FROM    DUAL;

SELECT  LOWER (ENAME)
FROM    EMP;

SELECT  EMPNO, ENAME, JOB
FROM    EMP
WHERE   LOWER (JOB) = 'manager';

SELECT  LENGTH('Oracle'), LENGTH('오라클')
FROM    DUAL;

SELECT  lengthb('Oracle'), lengthb('오라클')
FROM    DUAL;

SELECT  SUBSTR('Welcome to Oracle', 4, 3)
FROM    DUAL;

SELECT  SUBSTR('Welcome to Oracle', -4, 4)
FROM    DUAL;

SELECT  *
FROM    EMP;

SELECT  SUBSTR (HIREDATE, 1, 2) AS 년도, SUBSTR (HIREDATE, 4, 2) AS 달
FROM    EMP;

SELECT  *
FROM    EMP
WHERE   HIREDATE BETWEEN '81/01/01' AND '81/12/31';

SELECT  *
FROM    EMP
WHERE   HIREDATE >= '81/01/01'
AND     HIREDATE <= '81/12/31';

SELECT  *
FROM    EMP
WHERE   SUBSTR (HIREDATE, 1, 2) = 81;

SELECT  *
FROM    EMP
WHERE   ENAME LIKE '%E';

SELECT  *
FROM    EMP
WHERE   SUBSTR (ENAME, -1, 1) = 'E';

SELECT  substr ('웰컴투오라클', 3, 4), substrb ('웰컴투오라클', 3, 4)
FROM    DUAL;

SELECT  INSTR('Welcome to Oracle', 'O')
FROM    DUAL;

SELECT  INSTR('WELCOME TO ORACLE', 'O')
FROM    DUAL;

SELECT  INSTR('WELCOME TO ORACLE', 'O', 6, 2)
FROM    DUAL;


SELECT  EMPNO, ENAME
FROM    EMP
WHERE   ENAME LIKE '__R%';

--'직원들의 이름 중에서 세번째 글자가 R 인 사람'의 사원번호와 이름을 검색

SELECT  EMPNO, ENAME
FROM    EMP
WHERE   INSTR (ENAME, 'R', 3, 1) = 3;

SELECT  EMPNO, ENAME
FROM    EMP
WHERE   SUBSTR (ENAME, 3, 1) = 'R';


SELECT  LPAD('Oracle', 20, '#')
FROM    DUAL;

SELECT  RPAD('Oracle', 20, '#')
FROM    DUAL;

SELECT  TRIM('      Oracle      ')
FROM    DUAL;

SELECT  PLAYER_NAME||'님' AS 선수명, NICKNAME||'!!!'AS 별명
FROM    PLAYER
WHERE   NICKNAME IS NOT NULL;

SELECT  SYSDATE + 1
FROM    DUAL;

SELECT  SYSDATE - 1
FROM    DUAL;

SELECT  SYSDATE - HIREDATE AS "입사 후 근무일수"
FROM    EMP;

SELECT  *
FROM    EMP;



SELECT  ENAME AS 사원이름, FLOOR((SYSDATE - HIREDATE) / 365) AS 근속년수, TRUNC(SYSDATE - HIREDATE) AS 근무일수
FROM    EMP;

SELECT  ENAME, HIREDATE, 
        EXTRACT (YEAR FROM HIREDATE) AS 입사년도,
        LPAD(EXTRACT (MONTH FROM HIREDATE), 2, '0') AS 입사월,
        LPAD(EXTRACT (DAY FROM HIREDATE), 2, '0') AS 입사일,
        EXTRACT (DAY FROM SYSDATE) AS 현재날짜
FROM    EMP;

SELECT  ADD_MONTHS(SYSDATE, 1) 개월수를더하는함수
FROM    DUAL;

SELECT  ADD_MONTHS(SYSDATE, 4)
FROM    DUAL;

SELECT  ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 6)
FROM    EMP;

SELECT  SYSDATE, NEXT_DAY(SYSDATE, '수요일')
FROM    DUAL;

SELECT  SYSDATE, NEXT_DAY(SYSDATE, '화요일')
FROM    DUAL;

ALTER SESSION SET NLS_LANGUAGE = KOREAN;

SELECT  SYSDATE, LAST_DAY(SYSDATE)
FROM    DUAL;

SELECT  SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM    DUAL;

SELECT  EMPNO, ENAME, HIREDATE, TO_CHAR(HIREDATE, 'YYYY-MM-DD') AS 입사년도
FROM    EMP;

SELECT  SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM@DD*****DD')
FROM    DUAL;

SELECT  TO_CHAR(SYSDATE, 'YYYY-MM-DD, HH24:MI:SS')
FROM    DUAL;

SELECT  TO_CHAR(SYSDATE + 6/24, 'HH:MI:SS') AS 현재시간마지막시간, 
        TO_CHAR(SYSDATE + 7/24, 'HH:MI:SS') AS 다음날최초시간표시
FROM    DUAL;

SELECT  TO_CHAR(SYSDATE + 5/24, 'YYYY-MM-DD, HH24:MI:SS') AS 현재시간마지막시간, 
        TO_CHAR(SYSDATE + 6/24, 'YYYY-MM-DD, HH24:MI:SS') AS 다음날최초시간표시
FROM    DUAL;

