SELECT  SYSDATE - TO_DATE('2019-01-23', 'YYYY-MM-DD') 일단위
FROM    DUAL;

SELECT  (TO_DATE('2019-01-24 10:37:10', 'YYYY-MM-DD HH24:MI:SS')
        - TO_DATE('2019-01-24 10:36:10', 'YYYY-MM-DD HH24:MI:SS')) * (24*60*60) 초단위
FROM    DUAL;

SELECT  (TO_DATE('2019-01-24 11:36:10', 'YYYY-MM-DD HH24:MI:SS')
        - TO_DATE('2019-01-24 10:36:10', 'YYYY-MM-DD HH24:MI:SS')) * (24) 시단위
FROM    DUAL;

SELECT  (TO_DATE('2019-01-24 10:37:10', 'YYYY-MM-DD HH24:MI:SS')
        - TO_DATE('2019-01-24 10:36:10', 'YYYY-MM-DD HH24:MI:SS')) * (24*60) 분단위
FROM    DUAL;


SELECT  ENAME, SAL, COMM, JOB
FROM    EMP;

SELECT  ENAME, SAL, NVL(COMM,0), JOB
FROM    EMP;

--SELECT  ENAME, SAL, NVL(COMM, '널을 다른 값으로 표현하고자 하는 글'), JOB
--FROM    EMP;

SELECT  *
FROM    PLAYER;

SELECT  PLAYER_NAME, POSITION, NVL(POSITION, '없음') AS 포지션
FROM    PLAYER
WHERE   TEAM_ID = 'K08';


SELECT  ENAME, SAL, COMM, SAL*12+COMM AS "급여*12+커미션",
        NVL(COMM, 0) AS "COMM NULL 처리",
        SAL*12+NVL(COMM, 0) AS "연봉+커미션 결과"
FROM    EMP;

SELECT  *
FROM    EMP;

SELECT  EMPNO, ENAME, NVL(TO_CHAR(MGR), 'C  E  O') AS MANAGER
FROM    EMP
WHERE   MGR IS NULL;

SELECT  DEPTNO, ROUND(SAL, 3)
FROM    EMP;

SELECT  SUM(SAL)
FROM    EMP;

SELECT  SUM(SEAT_COUNT) AS 스타디움총좌석수
FROM    STADIUM;

SELECT  AVG(NVL(COMM, 0))
FROM    EMP;

SELECT  NVL(AVG(COMM), 0)
FROM    EMP;

SELECT  MAX(SAL) 최고급여, MIN(SAL) 최저급여, SUM(SAL) 사원총급여, AVG(SAL) 사원평균급여
FROM    EMP;

SELECT  MIN(SAL)
FROM    EMP;

SELECT  COUNT(EMPNO), COUNT(SAL), COUNT(*), COUNT(COMM)
FROM    EMP;


SELECT  MAX(SAL)
FROM    EMP
WHERE   DEPTNO IS NOT NULL
GROUP BY DEPTNO;



SELECT  MAX(HIREDATE) AS "막내의 입사일", MIN(HIREDATE) AS "최고참의 입사일"
FROM    EMP;

SELECT  COUNT(COMM) AS 사원수
FROM    EMP
WHERE   DEPTNO = 10;

--EMP 테이블에 존재하는 DEPTNO 컬럼의 값이 10이나 30인 ROW 중에서 COMM 컬럼의 값이 NULL이 아닌 수를 COUNT 한다.

SELECT  COUNT(COMM) AS 사원수
FROM    EMP
WHERE   DEPTNO = 10 OR DEPTNO = 30;

SELECT  *
FROM    EMP;

SELECT  *
FROM    PLAYER;

SELECT   DEPTNO, TRUNC(AVG(NVL(SAL, 0)), 1) AS 평균급여
FROM     EMP
GROUP BY DEPTNO;

SELECT   DEPTNO, SUM(SAL) AS 총급여
FROM     EMP
GROUP BY DEPTNO;

SELECT   POSITION, ROUND(AVG(NVL(HEIGHT)), 2) AS 평균키
FROM     PLAYER
GROUP BY POSITION;

