CREATE TABLE MEMBERS (
    MEMBERNO NUMBER NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL,
    PWD VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(50) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MEMBERNO_PK PRIMARY KEY(MEMBERNO);

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_EMAIL_UL UNIQUE(EMAIL);

CREATE SEQUENCE MEMBER_MEMBERNO_SEQ
INCREMENT BY 1
START WITH 1;

DESC MEMBERS;

--DROP SEQUENCE MAMBER_MEMBERNO_SEQ;

INSERT INTO MEMBERS
(MEMBERNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES
(MEMBER_MEMBERNO_SEQ.NEXTVAL, 'A1@TEST.COM', '1111', 
 '홍길동', SYSDATE, SYSDATE);
 
INSERT INTO MEMBERS
(MEMBERNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES
(MEMBER_MEMBERNO_SEQ.NEXTVAL, 'B1@TEST.COM', '2222', 
 '임꺽정', SYSDATE, SYSDATE);

SELECT  *
FROM    MEMBERS;

commit;

SELECT  MEMBERNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE
FROM    MEMBERS;

INSERT INTO MEMBERS
(MEMBERNO, EMAIL, PWD, MNAME, CRE_DATE, MOD_DATE)
VALUES
(MEMBER_MEMBERNO_SEQ.NEXTVAL, 'S3@TEST.COM', '3333',
'임지애', SYSDATE, SYSDATE);



 