--1번 문제
CREATE USER sampleuser IDENTIFIED BY sample12 account unlock;

GRANT CONNECT TO sampleuser; 

GRANT RESOURCE TO sampleuser;

SELECT *
FROM USER_ROLE_PRIVS;

DROP USER sampleuser;

--2번 문제

CREATE TABLE STUDENT
(
	STU_SEQ         NUMBER          CONSTRAINT STUDENT_STU_SEQ_PK PRIMARY KEY,
	NAME            VARCHAR2(50)    NOT NULL,
	EMAIL           VARCHAR2(100)   NOT NULL,
	ADDRESS         VARCHAR2(200),
	REG_DATE        DATE            NOT NULL
);

CREATE SEQUENCE SEQ_student_STU_SEQ 
    INCREMENT BY 1 START WITH 1;

CREATE TABLE SUBJECT
(
	SUBJECT_CODE    NUMBER          CONSTRAINT SUBJECT_subject_code_PK PRIMARY KEY,
	SUBJECT_NAME    VARCHAR2(20)    NOT NULL,
	CAPACITY        NUMBER(3)       DEFAULT 0 NOT NULL,
	OPEN_DATE       DATE            NOT NULL
	
);

CREATE SEQUENCE SEQ_subject_subject_code 
    INCREMENT BY 1 START WITH 1;

CREATE TABLE EDUCATION_LOG
(
	STU_SEQ         NUMBER          NOT NULL,
	SUBJECT_CODE    NUMBER          NOT NULL,
	LECT_START_DATE DATE            CONSTRAINT LECT_START_DATE_PK PRIMARY KEY,
	LECT_END_DATE   DATE,
	SCORE           NUMBER(5,2)
);

ALTER TABLE EDUCATION_LOG
	ADD FOREIGN KEY (STU_SEQ)
	REFERENCES STUDENT (STU_SEQ);

ALTER TABLE EDUCATION_LOG
	ADD FOREIGN KEY (SUBJECT_CODE)
	REFERENCES SUBJECT (SUBJECT_CODE);

DESC STUDENT;

